"""create

Revision ID: 23e4c31d0dda
Revises: caccdd715bd4
Create Date: 2023-12-07 10:12:46.008195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e4c31d0dda'
down_revision: Union[str, None] = 'caccdd715bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###
