"""create tables

Revision ID: caccdd715bd4
Revises: 3e00fad1a645
Create Date: 2023-12-06 12:24:29.830887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caccdd715bd4'
down_revision: Union[str, None] = '3e00fad1a645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirm_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirm_password')
    # ### end Alembic commands ###
